# initial version generated by chatgpt
from arxiv import Search
import re
import sys

def search_arxiv_and_generate_link(paper_title):
    # Replace spaces with '+' for the arXiv search query
    #query = re.sub(r'\s+', '+', paper_title)
    query = paper_title
    #print(query)
    
    # Search on arXiv
    results = list(Search(query=query, max_results=10).results())

    for result in results:
        # Extract arXiv URL and paper title
        arxiv_url = result.entry_id
        pt = result.title
        if pt.lower() != paper_title.lower():
            continue

        # Generate HTML link
        return arxiv_url
    return ""

def process_file(filename):
    with open(filename) as f:
        for line in f.readlines():
            line = line.strip()
            arxiv_url = search_arxiv_and_generate_link(line)
            inner_html = f'<a href="{arxiv_url}">{line}</a>'
            print(f"<li><i>Reference:</i> {inner_html}</li>")

if __name__ == "__main__":
    process_file(sys.argv[1])

    # Example usage
    # paper_title = "Your Paper Title"
    # html_link = search_arxiv_and_generate_link(paper_title)
    # print(html_link)
